version: "3.3"

services:
  database:
    container_name: curso_django_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
      - POSTGRES_PASSWORD=pythonpro
      - POSTGRES_USER=pythonpro
    ports:
      - 5433:5432