version: "3.3"

services:
  app:
    build: .
    container_name: littlehelp_app
    command: python manage.py runserver 0.0.0.0:8000
  ports:
  - 8000:8000
  volumes:
  - .:/home/littlehelp/app
  depends_on:
  - db

  db:
  image: postgres
  container_name: littlehelp_db
  tty: true
  volumes:
  - .docker/.pgdata:/var/lib/postgresql/data
  environment:
  - POSTGRES_DB=littlehelp
  - POSTGRES_USER=root
  - POSTGRES_PASSWORD=littlehelp1234
